DROP TABLE IF EXISTS bi_gallery;
CREATE TABLE IF NOT EXISTS `bi_gallery` (
  `IGALLERYID` int(10) NOT NULL AUTO_INCREMENT,
  `IPHOTOID` int(16) NOT NULL,
  `IIMAGELOCATION` varchar(225) DEFAULT NULL,
  `ISHOWPUBLIC` int(10) DEFAULT NULL,
  `ICLIENTID` int(10) DEFAULT NULL,
  `IUSERID` int(10) DEFAULT NULL,
  PRIMARY KEY (`IGALLERYID`)
);

DROP TABLE IF EXISTS book_images;
CREATE TABLE IF NOT EXISTS `book_images` (
  `IPHOTOID` int(16) NOT NULL AUTO_INCREMENT,
  `IRECORDNUMBER` int(10) unsigned NOT NULL,
  `CLOCALLOCATION` varchar(225) DEFAULT NULL,
  `CREMOTELOCATION` varchar(225) DEFAULT NULL,
  `CIMAGEDESCRIPTION` varchar(225) DEFAULT NULL,
  `IPROGRESSNUMBER` int(11) DEFAULT NULL,
  `IIMAGECOUNT` int(11) DEFAULT NULL,
  `DCREATEDTIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`IPHOTOID`)
);

DROP TABLE IF EXISTS book_records;
CREATE TABLE IF NOT EXISTS `book_records` (
  `IRECORDNUMBER` int(6) NOT NULL AUTO_INCREMENT,
  `IORDERNUMBER` int(6) NOT NULL,
  `CFIRSTNAME` varchar(30) NOT NULL,
  `CLASTNAME` varchar(30) NOT NULL,
  `DDESCRIPTION` text NOT NULL,
  `IPRICE` varchar(12) NOT NULL,
  `CACCOUNTTYPE` varchar(30) NOT NULL,
  `CIMPUTTIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CPROGRESSTYPE` varchar(32) NOT NULL DEFAULT 'NoProgress',
  `CISDELETED` varchar(32) NOT NULL,
  `CPAYMENTSTATUS` varchar(32) NOT NULL DEFAULT 'NoPayment',
  `IUSERID` int(10) DEFAULT NULL,
  `IORDERNUMBERMD5` varchar(225) DEFAULT NULL,
  `IUSERIDMD5` varchar(225) DEFAULT NULL,
  `IMODIFIEDTIME` varchar(225) DEFAULT NULL,
  `ICLIENTID` int(10) DEFAULT NULL,
  `CTITLE` varchar(225) DEFAULT NULL,
  PRIMARY KEY (`IRECORDNUMBER`)
);

DROP TABLE IF EXISTS client_account;
CREATE TABLE IF NOT EXISTS `client_account` (
  `CUSERNAME` varchar(225) DEFAULT NULL,
  `CPASSWORD` varchar(225) DEFAULT NULL,
  `IISACTIVE` int(10) DEFAULT NULL,
  `ICLIENTID` int(10) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ICLIENTID`)
);

DROP TABLE IF EXISTS client_detail;
CREATE TABLE IF NOT EXISTS `client_detail` (
  `ICLIENTID` int(10) DEFAULT NULL,
  `CUSERNAMEDETAIL` varchar(225) DEFAULT NULL,
  `CLASTLOGIN` varchar(225) DEFAULT NULL,
  `ICOMCOUNT` int(10) DEFAULT NULL,
  `CFIRSTNAME` varchar(225) DEFAULT NULL,
  `CLASTNAME` varchar(225) DEFAULT NULL
);

DROP TABLE IF EXISTS com_comment;
CREATE TABLE IF NOT EXISTS `com_comment` (
  `ICLIENTID` int(10) DEFAULT NULL,
  `ICOMMENT` varchar(225) DEFAULT NULL,
  `ICREATEDTIME` varchar(225) DEFAULT NULL,
  `IRECORDNUMBER` int(10) DEFAULT NULL,
  `ICOMMENTID` int(10) NOT NULL AUTO_INCREMENT,
  `IUSERID` int(10) DEFAULT NULL,
  PRIMARY KEY (`ICOMMENTID`)
);

DROP TABLE IF EXISTS com_request;
CREATE TABLE IF NOT EXISTS `com_request` (
  `ICLIENTID` int(10) DEFAULT NULL,
  `CREQUESTTITLE` varchar(225) DEFAULT NULL,
  `CDESCRIPTION` varchar(225) DEFAULT NULL,
  `CRESPONCESTATUS` varchar(225) DEFAULT NULL,
  `CRESPONCE` varchar(225) DEFAULT NULL,
  `IISAPPROVED` int(10) DEFAULT NULL,
  `ICREATEDTIME` varchar(225) DEFAULT NULL,
  `IMODIFIEDTIME` varchar(225) DEFAULT NULL,
  `IREQUESTID` int(10) NOT NULL AUTO_INCREMENT,
  `IUSERID` int(10) DEFAULT NULL,
  `IREQUESTPRICE` varchar(225) DEFAULT NULL,
  PRIMARY KEY (`IREQUESTID`)
);

DROP TABLE IF EXISTS errorLogs;
CREATE TABLE IF NOT EXISTS `errorLogs` (
  `ILOGID` int(10) NOT NULL AUTO_INCREMENT,
  `CSHORTVALUE` varchar(225) DEFAULT NULL,
  `CLONGVALUE` text DEFAULT NULL,
  `ICREATEDTIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IUSERID` int(11) DEFAULT NULL,
  `ICLIENTID` int(11) DEFAULT NULL,
  `IISARCHIVED` int(1) DEFAULT NULL,
  PRIMARY KEY (`ILOGID`)
);

DROP TABLE IF EXISTS hack_attempt;
CREATE TABLE IF NOT EXISTS `hack_attempt` (
  `ICLIENTID` int(10) DEFAULT NULL,
  `IUSERID` int(10) DEFAULT NULL,
  `ICREATEDTIME` varchar(225) DEFAULT NULL,
  `CHACKTEXT` varchar(225) DEFAULT NULL,
  `IHACKID` int(10) NOT NULL AUTO_INCREMENT,
  `IHACKLOCATION` varchar(225) DEFAULT NULL,
  `IIPADDRESS` varchar(225) DEFAULT NULL,
  PRIMARY KEY (`IHACKID`)
);

DROP TABLE IF EXISTS ip_ban;
CREATE TABLE IF NOT EXISTS `ip_ban` (
  `IIPADDRESS` varchar(225) DEFAULT NULL,
  `ICREATEDTIME` varchar(225) DEFAULT NULL,
  `IISBANNED` int(10) DEFAULT NULL,
  `ICLIENTID` varchar(225) DEFAULT NULL,
  `IUSERID` varchar(225) DEFAULT NULL
);

DROP TABLE IF EXISTS lockdown;
CREATE TABLE IF NOT EXISTS `lockdown` (
  `CALLOWEDUSER` varchar(225) DEFAULT NULL
);

DROP TABLE IF EXISTS user_account;
CREATE TABLE IF NOT EXISTS `user_account` (
  `CUSERNAME` varchar(225) DEFAULT NULL,
  `CPASSWORD` varchar(225) DEFAULT NULL,
  `CPASSWORD2` varchar(225) DEFAULT NULL,
  `IUSERID` int(10) NOT NULL AUTO_INCREMENT,
  `IISACTIVE` int(10) DEFAULT NULL,
  PRIMARY KEY (`IUSERID`)
);

DROP TABLE IF EXISTS user_detail;
CREATE TABLE IF NOT EXISTS `user_detail` (
  `IUSERID` int(10) DEFAULT NULL,
  `CUSERNAMEDETAIL` varchar(225) DEFAULT NULL,
  `CLASTLOGIN` varchar(225) DEFAULT NULL,
  `IRECORDCOUNT` int(10) DEFAULT NULL DEFAULT '0',
  `IUSERIDMD5` varchar(225) DEFAULT NULL
);

DROP TABLE IF EXISTS user_settings;
CREATE TABLE IF NOT EXISTS `user_settings` (
  `ISETTINGID` int(10) NOT NULL AUTO_INCREMENT,
  `CTYPE` varchar(225) DEFAULT NULL,
  `CVALUE` varchar(225) DEFAULT NULL,
  `IUSERID` int(11) DEFAULT NULL,
  `COTHERFIELD` varchar(225) DEFAULT NULL,
  `ICURRENCYTYPE` int(1) DEFAULT NULL,
  PRIMARY KEY (`ISETTINGID`)
);
