<?php
	function getEnvString() {
		$envString = <<<ENV
DATABASE_LOCATION = localhost
DATABASE = TEST_DB
USER = TEST_USER
PASS = TEST_PASS
SALT = test_str_HASH_sAlT
HASH_COST = 10
#
DEVELOPMENT = 1
DEBUGGING = 0
SHOW_SUPERUSER_GALLERY = 1
PUBLIC_COMMISSIONER_REG = 1
#
IMAGE_LIB = clientside/
UPLOAD_SIZE_LIMIT = 5
ENV;
	return $envString;
	}
?>