<style>
a.footer-left
{
	position: fixed;
	bottom: 0;
	left: 0;
	margin-left: 10px;
	margin-bottom: 10px;
	text-align: left;
}
a.footer-right
{
	position: fixed;
	bottom: 0;
	right: 0;
	margin-bottom: 10px;
	margin-right: 10px;
	text-align: right;
}
</style>
	<div class="footer">
		<!--<a href="/termsOfService.php" class="footer-left">Terms of Service</a>-->
		<a href="/privacyPolicy.php" class="footer-right">Privacy Policy</a>
	</div>
</body>
</html>
